// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOwN1H5inghC7DxHn3S31f7KZmr3PDhQ',
    appId: '1:489293153996:web:9bb952de098d89764a2469',
    messagingSenderId: '489293153996',
    projectId: 'flat-finder-7dfcd',
    authDomain: 'flat-finder-7dfcd.firebaseapp.com',
    storageBucket: 'flat-finder-7dfcd.firebasestorage.app',
    measurementId: 'G-VN15WGEMJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrOwN1H5inghC7DxHn3S31f7KZmr3PDhQ',
    appId: '1:489293153996:android:78c13c3c5d458d9a198592',
    messagingSenderId: '489293153996',
    projectId: 'flat-finder-7dfcd',
    storageBucket: 'flat-finder-7dfcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCArO5gJE50tNbUw3Jd8pFfCv8xmg6RE',
    appId: '1:45592465367:ios:your_ios_app_id_here',
    messagingSenderId: '45592465367',
    projectId: 'flat-finder-2122d',
    storageBucket: 'flat-finder-2122d.firebasestorage.app',
    iosBundleId: 'com.example.flatFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNCArO5gJE50tNbUw3Jd8pFfCv8xmg6RE',
    appId: '1:45592465367:ios:your_ios_app_id_here',
    messagingSenderId: '45592465367',
    projectId: 'flat-finder-2122d',
    storageBucket: 'flat-finder-2122d.firebasestorage.app',
    iosBundleId: 'com.example.flatFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrOwN1H5inghC7DxHn3S31f7KZmr3PDhQ',
    appId: '1:489293153996:web:9bb952de098d89764a2469',
    messagingSenderId: '489293153996',
    projectId: 'flat-finder-7dfcd',
    authDomain: 'flat-finder-7dfcd.firebaseapp.com',
    storageBucket: 'flat-finder-7dfcd.firebasestorage.app',
    measurementId: 'G-VN15WGEMJW',
  );
}